// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhA61hEZPQSl-1nemaGyqmCkFWCreloU',
    appId: '1:967590606238:web:4fed7bcc418901e04b528f',
    messagingSenderId: '967590606238',
    projectId: 'myapp-d602c',
    authDomain: 'myapp-d602c.firebaseapp.com',
    storageBucket: 'myapp-d602c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MDXayAy4L9XnUxvSWJ5eEYt2pKpy4RA',
    appId: '1:967590606238:android:d8d9aef78a3ad3e74b528f',
    messagingSenderId: '967590606238',
    projectId: 'myapp-d602c',
    storageBucket: 'myapp-d602c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ItglnT3dAK4QVn3tmcFYLbRFLbrvu4c',
    appId: '1:967590606238:ios:0828977dc07191514b528f',
    messagingSenderId: '967590606238',
    projectId: 'myapp-d602c',
    storageBucket: 'myapp-d602c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ItglnT3dAK4QVn3tmcFYLbRFLbrvu4c',
    appId: '1:967590606238:ios:0828977dc07191514b528f',
    messagingSenderId: '967590606238',
    projectId: 'myapp-d602c',
    storageBucket: 'myapp-d602c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWhA61hEZPQSl-1nemaGyqmCkFWCreloU',
    appId: '1:967590606238:web:f0067a09206c7c434b528f',
    messagingSenderId: '967590606238',
    projectId: 'myapp-d602c',
    authDomain: 'myapp-d602c.firebaseapp.com',
    storageBucket: 'myapp-d602c.firebasestorage.app',
  );

}